# Path relative to makefile
DATA_DIR := ./src/pandoc/

# Path relative to data_dir
SCRIPTS_DIR := $(DATA_DIR)/scripts/

# Common options
PANDOC_SLIDES = --standalone \
	--table-of-contents \
	--data-dir=$(DATA_DIR) \
	-i -t revealjs
